using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Npgsql;
using NSubstitute;
using POS.Application.Abstractions.Auth;
using POS.Application.Abstractions.Caching;
using POS.Application.Abstractions.Persistence;
using POS.Application.UseCases.Stores.Commands.AssignAdminToStore;
using POS.Domain.Common;
using POS.Domain.Employees;
using POS.Domain.Rbac;
using POS.Domain.Rbac.Constants;
using POS.Domain.Stores;
using POS.Infrastructure.Persistence;
using POS.Infrastructure.Persistence.Repositories;

namespace POS.Infrastructure.Tests.Stores;

public sealed class PostgresFactAttribute : FactAttribute
{
    public PostgresFactAttribute()
    {
        if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("POS_TEST_POSTGRES")))
            Skip = "Requires POS_TEST_POSTGRES for a dedicated PostgreSQL test database with CREATE SCHEMA permission.";
    }
}

public class StoreAssignmentConcurrencyTests
{
    [PostgresFact]
    [Trait("Category", "PostgreSQL")]
    public async Task Concurrent_transfer_rejects_stale_source_and_retry_checks_new_source_scope()
    {
        // Use an explicitly supplied test database. All objects are confined to a fresh
        // random schema generated by this test; never reset/migrate an existing database.
        var schema = "store_assignment_test_" + Guid.NewGuid().ToString("N");
        var settings = new NpgsqlConnectionStringBuilder(Environment.GetEnvironmentVariable("POS_TEST_POSTGRES"))
        {
            SearchPath = schema,
            Pooling = false
        };
        await using var admin = new NpgsqlConnection(settings.ConnectionString);
        await admin.OpenAsync();
        await using (var create = new NpgsqlCommand($"CREATE SCHEMA \"{schema}\"", admin))
            await create.ExecuteNonQueryAsync();

        try
        {
            var ownerRole = new Role(RoleNames.Owner, isSystemRole: true);
            var cashierRole = new Role(RoleNames.Cashier, isSystemRole: true);
            var managerRole = new Role(RoleNames.StoreManager, isSystemRole: true);
            var source = new Store("Source");
            var targetA = new Store("Target A");
            var targetB = new Store("Target B");
            var pinHash = BCrypt.Net.BCrypt.HashPassword("123456");
            var ownerA = new Employee("Owner A", "owner_a", "unused", pinHash, ownerRole.Id, isChainOwner: true);
            var ownerB = new Employee("Owner B", "owner_b", "unused", pinHash, ownerRole.Id, isChainOwner: true);
            var employee = new Employee("Cashier", "cashier", "unused", pinHash, cashierRole.Id, storeId: source.Id);

            await using (var seed = CreateContext(settings.ConnectionString))
            {
                await seed.Database.ExecuteSqlRawAsync(seed.Database.GenerateCreateScript());
                seed.Roles.AddRange(ownerRole, cashierRole, managerRole);
                seed.Stores.AddRange(source, targetA, targetB);
                seed.Employees.AddRange(ownerA, ownerB, employee);
                seed.Entry(employee).Property(e => e.PinLookupHash).CurrentValue = new string('a', 64);
                seed.EmployeeStoreAccesses.AddRange(
                    new EmployeeStoreAccess(ownerA.Id, source.Id, ownerA.Id),
                    new EmployeeStoreAccess(ownerA.Id, targetA.Id, ownerA.Id),
                    new EmployeeStoreAccess(ownerB.Id, source.Id, ownerB.Id),
                    new EmployeeStoreAccess(ownerB.Id, targetB.Id, ownerB.Id));
                await seed.SaveChangesAsync();
            }

            await using var contextA = CreateContext(settings.ConnectionString);
            await using var contextB = CreateContext(settings.ConnectionString);
            var readerA = new PausedEmployeeRepository(new EmployeeRepository(contextA), employee.Id);
            var readerB = new PausedEmployeeRepository(new EmployeeRepository(contextB), employee.Id);
            var cacheA = Substitute.For<ICacheService>();
            var cacheB = Substitute.For<ICacheService>();
            var handlerA = CreateHandler(contextA, readerA, ownerA.Id, cacheA);
            var handlerB = CreateHandler(contextB, readerB, ownerB.Id, cacheB);
            using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(30));

            var taskA = handlerA.Handle(new(targetA.Id, employee.Id), timeout.Token);
            var taskB = handlerB.Handle(new(targetB.Id, employee.Id), timeout.Token);
            try
            {
                // Both real transactions must read the old source before either writes.
                await Task.WhenAll(readerA.Read.Task, readerB.Read.Task).WaitAsync(timeout.Token);
                readerB.Continue.TrySetResult();
                var resultB = await taskB;
                Assert.True(resultB.IsSuccess, resultB.Error.Code);

                // B has committed S1 -> S3; A's earlier S1 authorization cannot be reused.
                readerA.Continue.TrySetResult();
                var resultA = await taskA;
                Assert.Equal("Persistence.ConcurrentModification", resultA.Error.Code);
                await cacheA.DidNotReceive().RemoveAsync(Arg.Any<string>(), Arg.Any<CancellationToken>());
                Assert.Empty(contextA.ChangeTracker.Entries());

                await using var verify = CreateContext(settings.ConnectionString);
                var persisted = await verify.Employees.SingleAsync(e => e.Id == employee.Id, timeout.Token);
                Assert.Equal(targetB.Id, persisted.StoreId);
                Assert.Equal(managerRole.Id, persisted.RoleId);
                Assert.Equal(pinHash, persisted.PinHash);

                // A does not have access to S3. A fresh request must now return Forbidden.
                var retry = await CreateHandler(verify, new EmployeeRepository(verify), ownerA.Id, cacheA)
                    .Handle(new(targetA.Id, employee.Id), timeout.Token);
                Assert.Equal(ErrorType.Forbidden, retry.Error.Type);
            }
            finally
            {
                readerA.Continue.TrySetResult();
                readerB.Continue.TrySetResult();
                await timeout.CancelAsync();
                // Finish/dispose both transactions before removing this test's schema.
                try { await Task.WhenAll(taskA, taskB); } catch (OperationCanceledException) { }
            }
        }
        finally
        {
            await using var drop = new NpgsqlCommand($"DROP SCHEMA \"{schema}\" CASCADE", admin);
            await drop.ExecuteNonQueryAsync();
        }
    }

    private static AppDbContext CreateContext(string connectionString) =>
        new(new DbContextOptionsBuilder<AppDbContext>().UseNpgsql(connectionString).Options);

    private static AssignAdminToStoreCommandHandler CreateHandler(
        AppDbContext context, IEmployeeRepository employees, Guid callerId, ICacheService cache)
    {
        var currentUser = Substitute.For<ICurrentUser>();
        currentUser.IsAuthenticated.Returns(true);
        currentUser.EmployeeId.Returns(callerId);
        return new(new StoreRepository(context), employees, new RoleRepository(context),
            new EmployeeStoreAccessRepository(context), currentUser, new UnitOfWork(context), cache,
            NullLogger<AssignAdminToStoreCommandHandler>.Instance);
    }

    // Only coordinates the test's scheduling; all reads, predicates, writes, constraints
    // and transactions use the real repositories and PostgreSQL provider.
    private sealed class PausedEmployeeRepository(IEmployeeRepository inner, Guid targetId) : IEmployeeRepository
    {
        public Task AddAsync(Employee employee, CancellationToken cancellationToken = default) => inner.AddAsync(employee, cancellationToken);
        public Task<Employee?> GetDetailAsync(Guid id, CancellationToken cancellationToken = default) => inner.GetDetailAsync(id, cancellationToken);
        public Task<bool> ExistsByUsernameAsync(string username, CancellationToken cancellationToken = default) => inner.ExistsByUsernameAsync(username, cancellationToken);
        public Task<int> CountActiveOwnersInStoreAsync(Guid? storeId, CancellationToken cancellationToken = default) => inner.CountActiveOwnersInStoreAsync(storeId, cancellationToken);
        public Task<(List<Employee> Items, int TotalCount)> GetPagedAsync(Guid? storeId, Guid? employeeId,
            Guid? roleId, string? search, bool? isActive, int pageNumber, int pageSize, CancellationToken cancellationToken = default) =>
            inner.GetPagedAsync(storeId, employeeId, roleId, search, isActive, pageNumber, pageSize, cancellationToken);
        public TaskCompletionSource Read { get; } = new(TaskCreationOptions.RunContinuationsAsynchronously);
        public TaskCompletionSource Continue { get; } = new(TaskCreationOptions.RunContinuationsAsynchronously);

        public async Task<Employee?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default)
        {
            var employee = await inner.GetByIdAsync(id, cancellationToken);
            if (id == targetId)
            {
                Read.TrySetResult();
                await Continue.Task.WaitAsync(cancellationToken);
            }
            return employee;
        }

        public Task<Employee?> GetByUsernameWithRoleAndStoreAsync(
            string username,
            CancellationToken cancellationToken = default) =>
            inner.GetByUsernameWithRoleAndStoreAsync(username, cancellationToken);

        public Task<Employee?> GetByStoreAndPinLookupHashWithRoleAndStoreAsync(
            Guid storeId,
            string pinLookupHash,
            CancellationToken cancellationToken = default) =>
            inner.GetByStoreAndPinLookupHashWithRoleAndStoreAsync(
                storeId, pinLookupHash, cancellationToken);

        public Task<bool> HasPinConflictAsync(Guid employeeId, Guid storeId, string pinLookupHash, CancellationToken cancellationToken = default) =>
            inner.HasPinConflictAsync(employeeId, storeId, pinLookupHash, cancellationToken);
        public Task<bool> HasMissingPinLookupAsync(Guid storeId, CancellationToken cancellationToken = default) =>
            inner.HasMissingPinLookupAsync(storeId, cancellationToken);
        public Task<bool> HasOpenShiftOutsideStoreAsync(Guid employeeId, Guid storeId, CancellationToken cancellationToken = default) =>
            inner.HasOpenShiftOutsideStoreAsync(employeeId, storeId, cancellationToken);
    }
}
